# Generated by Django 4.2 on 2023-04-11 10:48

from django.db import migrations, models

import lyprox.loggers
import lyprox.riskpredictor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repo_url', models.URLField(default='https://github.com/rmnldwg/lynference')),
                ('revision', models.CharField(default='main', max_length=40)),
                ('params_path', models.CharField(default='params.yaml', max_length=100)),
                ('params', models.JSONField(default=dict)),
                ('risk_matrices', models.FileField(upload_to=lyprox.riskpredictor.models.get_path_for_risk_matrices)),
                ('num_samples', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'unique_together': {('git_repo_url', 'revision')},
            },
            bases=(lyprox.loggers.ModelLoggerMixin, models.Model),
        ),
    ]
