# Generated by Django 4.2.16 on 2025-02-05 15:14

from django.db import migrations, models
import lyprox.loggers


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InferenceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repo_name",
                    models.CharField(default="rmnldwg/lynference", max_length=50),
                ),
                ("ref", models.CharField(default="main", max_length=40)),
                (
                    "graph_config_path",
                    models.CharField(default="graph.ly.yaml", max_length=100),
                ),
                (
                    "model_config_path",
                    models.CharField(default="model.ly.yaml", max_length=100),
                ),
                (
                    "dist_configs_path",
                    models.CharField(default="distributions.ly.yaml", max_length=100),
                ),
                (
                    "samples_path",
                    models.CharField(default="models/samples.hdf5", max_length=100),
                ),
                ("num_samples", models.PositiveIntegerField(default=100)),
            ],
            options={
                "unique_together": {
                    (
                        "repo_name",
                        "ref",
                        "graph_config_path",
                        "model_config_path",
                        "dist_configs_path",
                        "samples_path",
                    )
                },
            },
            bases=(lyprox.loggers.ModelLoggerMixin, models.Model),
        ),
    ]
