# Generated by Django 3.1.6 on 2021-03-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('age', models.IntegerField()),
                ('diagnose_date', models.DateField()),
                ('alcohol_abuse', models.BooleanField(blank=True, null=True)),
                ('nicotine_abuse', models.BooleanField(blank=True, null=True)),
                ('hpv_status', models.BooleanField(blank=True, null=True)),
                ('t_stage', models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], default=0)),
                ('n_stage', models.PositiveSmallIntegerField(choices=[(0, 'N0'), (1, 'N1'), (2, 'N2'), (3, 'N3')])),
                ('m_stage', models.PositiveSmallIntegerField(choices=[(0, 'M0'), (1, 'M1'), (2, 'MX')])),
            ],
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'oral cavity'), (1, 'oropharynx'), (2, 'hypopharynx'), (3, 'larynx')])),
                ('subsite', models.CharField(choices=[('oral cavity', (('C03.0', 'Upper Gum'), ('C03.1', 'Lower gum'), ('C03.9', 'Gum, NOS'), ('C04.0', 'Anterior floor of mouth'), ('C04.1', 'Lateral floor of mouth'), ('C04.8', 'Overlapping lesion of floor of mouth'), ('C04.9', 'Floor of mouth, NOS'), ('C05.0', 'Hard palate'), ('C05.1', 'Soft palate, NOS'), ('C05.2', 'Uvula'), ('C05.8', 'Overlapping lesion of palate'), ('C05.9', 'Palate, NOS'), ('C06.0', 'Cheeck mucosa'), ('C06.1', 'Vestibule of mouth'), ('C06.2', 'Retromolar area'), ('C06.8', 'Overlapping lesion of other and unspecified parts of mouth'), ('C06.9', 'Mouth, NOS'))), ('oropharynx', (('C01.9', 'Base of tongue, NOS'), ('C09.0', 'Tonsillar fossa'), ('C09.1', 'Tonsillar pillar'), ('C09.8', 'Overlapping lesion of tonsil'), ('C09.9', 'Tonsil, NOS'), ('C10.0', 'Vallecula'), ('C10.1', 'Anterior surface of epiglottis'), ('C10.2', 'Lateral wall of oropharynx'), ('C10.3', 'Posterior wall of oropharynx'), ('C10.4', 'Branchial cleft'), ('C10.8', 'Overlapping lesions of oropharynx'), ('C10.9', 'Oropharynx, NOS'))), ('hypopharynx', (('C12.9', 'Pyriform sinus'), ('C13.0', 'Postcricoid region'), ('C13.1', 'Hypopharyngeal aspect of aryepiglottic fold'), ('C13.2', 'Posterior wall of hypopharynx'), ('C13.8', 'Overlapping lesion of hypopharynx'), ('C13.9', 'Hypopharynx, NOS'))), ('larynx', (('C32.0', 'Glottis'), ('C32.1', 'Supraglottis'), ('C32.2', 'Subglottis'), ('C32.3', 'Laryngeal cartilage'), ('C32.8', 'Overlapping lesion of larynx'), ('C32.9', 'Larynx, NOS')))], max_length=10)),
                ('position', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('central', 'central')], max_length=10)),
                ('extension', models.BooleanField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('t_stage', models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')])),
                ('stage_prefix', models.CharField(choices=[('c', 'c'), ('p', 'p')], max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.PositiveSmallIntegerField(choices=[(0, 'CT'), (1, 'MRI'), (2, 'PET'), (3, 'FNA'), (4, 'path'), (5, 'pCT')])),
                ('diagnose_date', models.DateField(blank=True, null=True)),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=10)),
                ('I', models.BooleanField(blank=True, null=True)),
                ('Ia', models.BooleanField(blank=True, null=True)),
                ('Ib', models.BooleanField(blank=True, null=True)),
                ('II', models.BooleanField(blank=True, null=True)),
                ('IIa', models.BooleanField(blank=True, null=True)),
                ('IIb', models.BooleanField(blank=True, null=True)),
                ('III', models.BooleanField(blank=True, null=True)),
                ('IV', models.BooleanField(blank=True, null=True)),
                ('V', models.BooleanField(blank=True, null=True)),
                ('VII', models.BooleanField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
