# Generated by Django 3.1.6 on 2021-02-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('age', models.IntegerField()),
                ('alcohol_abuse', models.BooleanField()),
                ('nicotine_abuse', models.BooleanField()),
                ('hpv_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose_date', models.DateField()),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'oral cavity'), (1, 'oropharynx'), (2, 'hypopharynx'), (3, 'larynx')])),
                ('t_stage', models.PositiveSmallIntegerField(choices=[(0, 'T0'), (1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')])),
                ('stage_prefix', models.CharField(choices=[('c', 'c'), ('p', 'p')], max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.PositiveSmallIntegerField(choices=[(0, 'radiotherapy'), (1, 'chemotherapy'), (2, 'surgery'), (3, 'immunotherapy')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose_date', models.DateField()),
                ('n_stage', models.PositiveSmallIntegerField(choices=[(0, 'N0'), (1, 'N1'), (2, 'N2'), (3, 'N3')])),
                ('m_stage', models.PositiveSmallIntegerField(choices=[(0, 'M0'), (1, 'M1')])),
                ('lnl_I', models.BooleanField(blank=True, default=None, null=True)),
                ('lnl_II', models.BooleanField(blank=True, default=None, null=True)),
                ('lnl_III', models.BooleanField(blank=True, default=None, null=True)),
                ('lnl_IV', models.BooleanField(blank=True, default=None, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
