# Generated by Django 3.1.6 on 2021-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumor',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'oral cavity'), (1, 'oropharynx'), (2, 'hypopharynx'), (3, 'larynx')], null=True),
        ),
    ]
