# Generated by Django 3.1.6 on 2021-02-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Therapy',
            new_name='Treatment',
        ),
    ]
