# Generated by Django 3.1.6 on 2021-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='diagnose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
