# Generated by Django 3.1.6 on 2021-02-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumor',
            name='position',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='left', max_length=10),
            preserve_default=False,
        ),
    ]
