# Generated by Django 3.1.6 on 2021-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='neck_dissection',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
