# Generated by Django 3.1.6 on 2021-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210223_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='modality',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CT'), (1, 'MRI'), (2, 'PET'), (3, 'FNA'), (4, 'neck dissection')], default=None),
            preserve_default=False,
        ),
    ]
