# Generated by Django 3.1.6 on 2021-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210311_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='identifier',
            new_name='hash_value',
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')]),
        ),
    ]
