# Generated by Django 3.1.6 on 2021-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_tumor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='lnl_I',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='lnl_II',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='lnl_III',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='lnl_IV',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alcohol_abuse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nicotine_abuse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
