# Generated by Django 3.1.6 on 2021-02-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_diagnose_modality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
