# Generated by Django 3.1.6 on 2021-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210301_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'T0'), (1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], default=0),
            preserve_default=False,
        ),
    ]
