# Generated by Django 3.1.6 on 2021-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_t_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], default=0),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')]),
        ),
    ]
