# Generated by Django 4.2.7 on 2023-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_dataset_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'T0'), (1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], default=0),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='t_stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'T0'), (1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')]),
        ),
    ]
