# Generated by Django 4.2.15 on 2024-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_t_stage_alter_tumor_t_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='m_stage',
            field=models.SmallIntegerField(choices=[(0, 'M0'), (1, 'M1'), (-1, 'MX')], default=0),
        ),
    ]
