# Generated by Django 4.0.5 on 2022-06-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='is_hidden',
        ),
    ]
