# Generated by Django 3.2 on 2021-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='institution_logos/'),
        ),
    ]
