# Generated by Django 4.2.19 on 2025-02-18 09:27

from django.db import migrations, models
import django.db.models.deletion
import lyprox.loggers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("subsite", models.CharField(max_length=100)),
                ("repo_name", models.CharField(max_length=100)),
                ("ref", models.CharField(max_length=100)),
                ("is_private", models.BooleanField(default=False)),
                ("last_pushed", models.DateTimeField()),
                ("last_saved", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.institution",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "institution", "subsite")},
            },
            bases=(lyprox.loggers.ModelLoggerMixin, models.Model),
        ),
    ]
