# Generated by Django 4.2.16 on 2025-02-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("dataexplorer", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datasetmodel",
            unique_together={("year", "institution", "subsite")},
        ),
    ]
