# Generated by Django 3.2 on 2022-03-17 17:00

from django.db import migrations, models


def update_V_sublevels(apps, schema_editor):
    Diagnose = apps.get_model("patients", "Diagnose")
    for diagnose in Diagnose.objects.all():
        if diagnose.V == False:
            diagnose.Va = False
            diagnose.Vb = False
        diagnose.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_tumor_subsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='Va',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnose',
            name='Vb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(update_V_sublevels)
    ]
