# Generated by Django 3.2.8 on 2022-03-22 15:37

from django.db import migrations, models


def map_icd_codes(apps, schema_editor):
    Tumor = apps.get_model("patients", "Tumor")
    for tumor in Tumor.objects.all():
        if tumor.subsite == "C01.9":
            tumor.subsite = "C01"
            tumor.save()
        elif tumor.subsite == "C12.9":
            tumor.subsite = "C12"
            tumor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_V_sublevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumor',
            name='subsite',
            field=models.CharField(choices=[('oral cavity', (('C02.0', 'dorsal surface of tongue'), ('C02.1', 'border of tongue'), ('C02.2', 'ventral surface of tongue'), ('C02.3', 'anterior two thirds of tongue'), ('C02.4', 'lingual tonsil'), ('C02.8', 'overlapping sites of tongue'), ('C02.9', 'tongue, nos'), ('C03.0', 'upper gum'), ('C03.1', 'lower gum'), ('C03.9', 'gum, nos'), ('C04.0', 'anterior floor of mouth'), ('C04.1', 'lateral floor of mouth'), ('C04.8', 'overlapping lesion of floor of mouth'), ('C04.9', 'floor of mouth, nos'), ('C05.0', 'hard palate'), ('C05.1', 'soft palate, nos'), ('C05.2', 'uvula'), ('C05.8', 'overlapping lesion of palate'), ('C05.9', 'palate, nos'), ('C06.0', 'cheeck mucosa'), ('C06.1', 'vestibule of mouth'), ('C06.2', 'retromolar area'), ('C06.8', 'overlapping lesion(s) of NOS parts of mouth'), ('C06.9', 'mouth, nos'), ('C08.0', 'submandibular gland'), ('C08.1', 'sublingual gland'), ('C08.9', 'salivary gland, nos'))), ('oropharynx', (('C01', 'base of tongue, nos'), ('C09.0', 'tonsillar fossa'), ('C09.1', 'tonsillar pillar'), ('C09.8', 'overlapping lesion of tonsil'), ('C09.9', 'tonsil, nos'), ('C10.0', 'vallecula'), ('C10.1', 'anterior surface of epiglottis'), ('C10.2', 'lateral wall of oropharynx'), ('C10.3', 'posterior wall of oropharynx'), ('C10.4', 'branchial cleft'), ('C10.8', 'overlapping lesions of oropharynx'), ('C10.9', 'oropharynx, nos'))), ('hypopharynx', (('C12', 'pyriform sinus'), ('C13.0', 'postcricoid region'), ('C13.1', 'hypopharyngeal aspect of aryepiglottic fold'), ('C13.2', 'posterior wall of hypopharynx'), ('C13.8', 'overlapping lesion of hypopharynx'), ('C13.9', 'hypopharynx, nos'))), ('larynx', (('C32.0', 'glottis'), ('C32.1', 'supraglottis'), ('C32.2', 'subglottis'), ('C32.3', 'laryngeal cartilage'), ('C32.8', 'overlapping lesion of larynx'), ('C32.9', 'larynx, nos')))], max_length=10),
        ),

        migrations.RunPython(map_icd_codes)
    ]
