# Generated by Django 4.0.4 on 2022-06-02 08:57

import core.loggers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0004_alter_tumor_subsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPatientTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_patients', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=patients.models.InstitutionPatientTable.get_file_path)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institution')),
            ],
            bases=(core.loggers.ModelLoggerMixin, models.Model),
        ),
    ]
