# Generated by Django 4.0.4 on 2022-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_csvtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvtable',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvtable',
            name='zenodo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
